### ISSUE TITLE
bigvideo.js (looping) not working on safari mac and ie10

### ISSUE THREAD

**Issue by pratibhasharma5** [dfcb/BigVideo.js#152]
i am using bigvideo.js plugin for background video with reference to tympanus.net/Tutorials/BigVideoSlideshow/ and it is working fine on linux system (chrome, IE, safari and firefox) but looping is not working in IE 10(windows) and safari(mac system)

**Comment by imanzano** [comment]
Hi,

Im using 1.1.5 version with Safari and the loop does not work.

  video = new $.BigVideo({useFlashForFirefox: false, container: videoWrap,loop:'true'});
                video.init();
                video.show([
                    {type: "video/mp4", src: "/images/landing/Syncofy-medium-29.mp4"},
                    {type: "video/webm", src: "/images/landing/Syncofy-medium-29.webm"},
                    {type: "video/ogg", src: "http://video-js.zencoder.com/oceans-clip.ogv"}
                ], {ambient: true});

Any idea ?

I tried doLoop , loop:'loop' as the documentation said but It doesn´t work. The loop works on chrome and firefox.

Best
Ignacio

**Comment by imanzano** [comment]
Fix.
I was using video.js 4.11 I have to switch to 4.3 and start working.

Best
Ignacio

**Comment by chandanucreate** [comment]
I am using video.js. its working fine in Mozilla but in chrome its not working in loop. Please suggest any idea.
