### ISSUE TITLE
.vjs-big-play-button selector is bad solution

### ISSUE THREAD

**Issue by vlatkodrljin** [dfcb/BigVideo.js#159]
Can you please replace in bigvideo.css

.vjs-big-play-button{display:none !important;}

with

#big-video-wrap .vjs-big-play-button{display:none !important;}

This is really bad if I want use video.js player and BigVideo.js library on my site separate. Button in my player is then always hidden...

Please ASAP

**Comment by hacfi** [comment]
This should be fixed indeed.

**Comment by vlatkodrljin** [comment]
Unfortunately, @johnpolacek is not up to date...

**Comment by hacfi** [comment]
You should create a PR to make it easier for him to merge this.
