### ISSUE TITLE
Requests for Video.js 5.0?

### ISSUE THREAD

**Issue by heff** [dfcb/BigVideo.js#162]
Hi @johnpolacek and other BigVideo contributors, we're working on Video.js 5.0 and since this is one of the more prominent projects built on Video.js it'd be great to get your feedback on things you'd like to see happen in the next major version. Any feedback is welcome.

**Comment by johnpolacek** [comment]
@heff Thanks! Hey I have unfortunately not been able to maintain BigVideo.js as much as it deserves. If you guys would be interested in taking it over, let me know!

**Comment by heff** [comment]
Ok, no problem. Would you want to help us build the cover/fit effect into video.js? What are the complicated pieces of it, and is it something we could build into video.js itself without adding additional wrapper elements?

**Comment by johnpolacek** [comment]
I would recommend implementing it as a plugin. Unfortunately, my availability is extremely limited at this time. Working full time on a small team at a rapidly scaling startup is a lot of fun, but unfortunately does not leave much time for open source work, at least not right now.

**Comment by heff** [comment]
Whatever, that's the best time to overload yourself with side projects! :-P (I started building Video.js on the side of Zencoder. That was fun...)

Thanks for the advice!
