### ISSUE TITLE
Controls appear for a split second then get removed. How do I stop this? 

### ISSUE THREAD

**Issue by SimonKomlos** [dfcb/BigVideo.js#165]
Here is a visual: ![videojs](https://cloud.githubusercontent.com/assets/9064902/8047985/2c10a5f0-0e1a-11e5-9527-6a249c1ad1c9.png)

Those controls appear for a split second then automatically go away. Is this a glitch or am I doing something wrong?

Here is my HTML: 
`<script src="jquery-min.js"></script>`
`<script src="video.js"></script>`
` <script src="bigvideo.js"></script>`

Javascript:
      `var opts = {
            controls: false,
            doLoop: true
        }`

`var BV = new $.BigVideo(opts);`
`BV.init();`
`BV.show('http://vjs.zencdn.net/v/oceans.mp4');`

What am I doing wrong? Thanks.

**Comment by hubdotcom** [comment]
Please try this:
<style>
.vjs-control-bar, .vjs-caption-settings{
    display:none!important;
}
</style>

**Comment by SimonKomlos** [comment]
@hubdotcom Yup, that worked! Thanks so much.

**Comment by hubdotcom** [comment]
You're welcome :)
