### ISSUE TITLE
Adding play pause and Video sound mute-unmute.

### ISSUE THREAD

**Issue by vivinblack** [dfcb/BigVideo.js#38]
I got this script to work fine with my videos ,But I want to put some controls over video page to play-pause and mute- un mute videos with those controls, How can I implement this?

**Comment by kibercoder** [comment]
Doing like me and be happy

			$(function() {
			    var BV = new $.BigVideo();
			    BV.init();
			    BV.show([
			        { 
			        	type: "video/mp4",  
			        	src: "http://kidwork.local/media/filmstudio_small.mp4", 
			    	},
			        { 
			        	type: "video/webm", 
			        	src: "http://kidwork.local/media/filmstudio.webm",
			        },
			        { 
			        	type: "video/ogg",  
			        	src: "http://kidwork.local/media/filmstudio.ogv",
			        }
    			]);

    			BV.getPlayer().volume(0);

				var v = document.getElementById("big-video-vid_html5_api");

				if (v != null) {

					$('#wrapper').click(function(){
						if (v.paused) {
						 	v.play();
						} else {
						 	v.pause();
						}
					});

				}


			});
