### ISSUE TITLE
Multiple videos in different containers

### ISSUE THREAD

**Issue by wilgrace** [dfcb/BigVideo.js#99]
Hi, apologies if this has been answered elsewhere...

I'm using a combination of FullPage.js and BigVideo.js to add fullscreen panels of images and video as the user scrolls down the page. Loading a video into a container anywhere on the page works fine (thanks!), but when I try to load in another to a different container the <video> tag appears without an video src.

This is what I'm calling:

$(function() {  

var TEST1 = new $.BigVideo({useFlashForFirefox:false, container:$('.video-wrapper1')});
var TEST2 = new $.BigVideo({useFlashForFirefox:false, container:$('.video-wrapper2')});

TEST1.init();
      TEST2.show('vids/river.mp4',{ambient:true});
TES2.init();
      TEST.show('vids/sherlockholmes.mp4',{ambient:true});

 });

Am I calling the videos incorrectly?
Does BigVideo support two videos in containers on the same page?

Thanks so much
Wil

**Comment by posykrat** [comment]
Is the feature planned soon ?

**Comment by thoughtpalette** [comment]
@posykrat with 4 PR's open, two from 2014, I doubt it. May as well fork and play around with it. Don't bother submitting a PR.
